### ISSUE TITLE
Prettier help strings.

### ISSUE THREAD

**Issue by bardes** [mpeterv/argparse#15] opened 2018-03-08 16:11 UTC
I know this is a bit on the opinion side but it would be nice to have linebreaks between the options for easier readability. I'd also change the way long options are listed
from:
```
-o <output>, --output <output>
                         Output file.
```
to:
```
--output <output>,
      -o <output>
                     Output file.
```
That is: stack multiple long options above each other, left pad them, and reduce the margin to allow for longer and more readable descriptions.

**Comment by mpeterv** [comment] 2018-03-17 12:07
I like the idea of having vertically aligned argument lists when displaying multiple aliases for an option. Probably not for simple flags though:

```
    -h,
--help
                     Show this help message and exit.
```

wastes too much space IMO.

Also, it makes sense to start outputting the description from the very first line if it fits after the option name and arguments. So, instead of 

```
--output <output>,
      -o <output>
                     Output file.
                     Some more words.
                     And more descriptions.
```

show this:

```
--output <output>,   Output file.
      -o <output>    Some more words.
                     And more descriptions.
```

**Comment by mpeterv** [comment] 2018-04-08 12:05
Implemented on master branch.

**Comment by mpeterv** [comment] 2018-04-08 12:10
I'll also add a way to space out help messages for different options with a parser property.

**Comment by mpeterv** [comment] 2018-04-08 13:06
Added parser properties on master branch:

* `help_vertical_space`: adds a number of extra new lines between blocks for different options or arguments in the help message, e.g. `parser:help_vertical_space(1)` for one empty line.
* `help_usage_margin`: sets number of spaces to put before usage string inside help message (3 by default).
* `help_description_margin`: sets margin for option and argument descriptions (25 by default).

Plus also `usage_margin` and `usage_max_witdh` for configuring generation of the usage string at the top of help.

**Comment by daurnimator** [comment] 2019-07-31 07:32
@bardes I think the issue is fixed? could you close it?

**Closed** 2019-07-31 15:54 UTC
